# .github/workflows/oidc-smoke.yml
name: OIDC Smoke Test
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure OIDC login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show account context
        run: az account show

      - name: List resource groups
        run: az group list --query "[].name" -o tsv
