name: CI - Build & Push

on:  
  push:
    branches: [ "master","main" ]
  
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read


jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build image
        working-directory: ./azure-vote  # path that contains Dockerfile; for the Azure Voting App it's the repo root
        run: |
          docker build -t ${{ vars.ACR_LOGIN_SERVER }}/voteapp:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ vars.ACR_LOGIN_SERVER }}/voteapp:${{ github.sha }}

      - name: Note image info
        run: echo "${{ vars.ACR_LOGIN_SERVER }}/voteapp:${{ github.sha }}" > image.txt

      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.txt
